#Fichero de configuracion
#Mon Sep 15 12:48:55 CEST 2025
email=yoel4352@gmail.com
nombre=Yoel
telefono=123456789
#Fichero de configuracion
#Mon Sep 15 12:49:35 CEST 2025
email=yoel4352@gmail.com
nombre=Yoel
telefono=123456789
#Fichero de configuracion
#Mon Sep 15 12:52:58 CEST 2025
\ =\ 
email=yoel4352@gmail.com
nombre=Yoel
telefono=123456789
